### ISSUE TITLE
TypeScript types

### ISSUE THREAD

**Issue by schickling** [sqlite/sqlite-wasm#1]
Would be nice if this library would provide TS types as well. I'm using the following WIP types in my app locally right now:

```ts
// TODO remove this once `@sqlite.org/sqlite-wasm` has types
declare module '@sqlite.org/sqlite-wasm' {
  export type TODO = any

  interface Window {
    // eslint-disable-next-line @typescript-eslint/consistent-type-imports
    sqlite3InitModule: (_?: TODO) => Promise<import('./sqlite3').Sqlite3>
  }

  export type Sqlite3 = {
    oo1: {
      DB: new (options?: OO1DBOptions) => DB
      OpfsDb: new (filename: string, mode: string) => DB
    }
    opfs?: {
      debug: TODO
      deleteEntry: TODO
      entryExists: TODO
      metrics: TODO
      mkdir: TODO
      randomFilename: TODO
      registerVfs: TODO
      rootDirectory: TODO
    }
    capi: {
      sqlite3_deserialize: TODO
      [key: string]: TODO
    }
    wasm: {
      allocFromTypedArray: (typedArray: Uint8Array) => number
      [key: string]: TODO
    }
  }

  /** https://sqlite.org/wasm/doc/trunk/api-oo1.md#db-ctor */
  export type OO1DBOptions = {
    /** @default ':memory:' */
    filename?: string
    /** open-mode flags */
    flags?: string
    /** name of the sqlite3_vfs to use */
    vfs?: string
  }

  export declare const InitWasm: () => Promise<Sqlite3>

  export default InitWasm

  export class DB {
    filename: string
    pointer: TODO

    affirmOpen(): DB

    changes(total: boolean, sixtyFour: boolean): number

    exec(options: ExecOptions): TODO
    exec(query: FlexibleString, options?: ExecOptions): TODO
    close(): DB
    export(): TODO
    /**
     * @example aDb.prepare("INSERT INTO foo(a) VALUES(?)").bind(123).stepFinalize();
     */
    prepare(query: FlexibleString): Stmt

    checkRc(db: TODO, resultCode: TODO)

    createFunction(): TODO

    dbFilename(): string

    dbName(): string
  }

  export type ExecOptions = {
    sql?: FlexibleString
    bind?: Bindable
    // saveSql?: TODO

    returnValue?: 'this' | 'resultRows' | 'saveSql'

    rowMode?: 'array' | 'object' | 'stmt'

    resultRows?: TODO[]
  }

  export type FlexibleString = string | Uint8Array | Int8Array | string[]

  /** https://sqlite.org/wasm/doc/trunk/api-oo1.md#stmt-properties */
  export interface Stmt {
    columnCount: number
    parameterCount: number
    pointer: TODO

    bind(bindable: Bindable): Stmt
    bind(indexOrParameterName: number | string, bindable: Bindable): Stmt

    stepFinalize(): boolean
  }

  export type Bindable = BindableValue[] | Record<string, BindableValue>

  export type BindableValue = null | undefined | number | boolean | string | Uint8Array | Int8Array
}

```

**Comment by schickling** [comment]
> This looks pretty complete.

It's actually not. 🙈 It has a ton of `TODO`s in there, so I hope someone else can take this as a foundation to create a more "complete" PR. 🙏

**Comment by sgbeal** [comment]
Please do not export the sqlite3.opfs namespace. That one is very specifically not intended for client-side use and is subject to change in any given build. Only namespaces described at:

https://sqlite.org/wasm/doc/trunk/api-index.md#namespace

should be exported.

**Comment by sgbeal** [comment]
PS: within the sqlite project, none of us use TypeScript (nor any node.js-related stuff beyond what emscripten requires for its behind-the-scenes work), so we make no effort to maintain this type of detail in the canonical tree. That's also the reason we don't use jsdoc doc syntax: we don't use any tools which can process them and don't want to add dependencies on tools we wouldn't otherwise use.

**Comment by sgbeal** [comment]
i need to leave for a couple of hours but will attempt to flesh out some of those here in the comments when i get back. e.g. `DB.pointer` is either `undefined` or an integer (WASM heap pointer).

**Comment by tomayac** [comment]
Let me take @schickling's types draft to a draft PR, and we can noodle on it there.

**Comment by tomayac** [comment]
Here we go: https://github.com/tomayac/sqlite-wasm/pull/2.

**Comment by tomayac** [comment]
Sorry, @schickling, just realized it's Johannes, not Jonas. Fixed in my comment above. I have invited you as a collaborator to the project.

**Comment by sgbeal** [comment]
Some notes/suggestions/caveats re. types:

- `pointer` type = `undefined | integerZeroOrGreater`
- The various DB constructors all accept `(string name, string mode)` as well as `(OO1DBOptions options)` formats.
- The `sqlite3.capi` namespace is huge and adding full typing info for it would be a significant undertaking. The list of functions and `SQLITE_...` constants exported there are listed in <https://sqlite.org/wasm/doc/trunk/module-symbols.html>, and the functions each link to their docs (many of which are the C API docs). That page also lists the public APIs of the `sqlite3.wasm` namespace, but does not link to their docs (<https://sqlite.org/wasm/doc/trunk/api-wasm.md>).
- The arguments for `sqlite3InitModule()` are not _strictly_ public or stable. They are passed on directly to the Emscripten module-loading interface, so technically support anything that API does (noting that that API is subject to unpredictable change), but we don't encourage use of that argument because its handling is out of our control. The module-loading process does not give us a way to intercept or normalize those arguments, so clients cannot rely on any given module-loading options long-term.
- FlexibleString: may also be of type `integerZeroOrGreater`, in which case a WASM heap pointer to a UTF-8-encoded `([const] char *)` is assumed. It may be of note that FlexibleStrings provided in Uint8Array and Int8Array form are _required_ to be in UTF-8 encoding. Those given in string or `string[]` form will be recoded from JS to UTF-8 automatically. 

That's all that comes to mind at the moment.

**Comment by mizchi** [comment]
Here is my personal workaround of the type definition.

https://gist.github.com/mizchi/cb572eae55154ec781ced5c111621939

My version also expresses a pattern where the return value changes with the exec argument (`returnValue` and `rowMode`), but I don't think it's necessary to try hard to define strict return values on the API. Strictness as TypeScript should be guaranteed by an ORM that wraps sqlite-wasm, for example.

I think what the average user wants is an OO1 API, so as a first step, it would be nice to have the types there.

However, as you can see from [official cookbook](https://sqlite.org/wasm/doc/trunk/cookbook.md) and other sources, the low-level `sqlite3.capi.*` also looks unavoidable. At the very least, it might be nice to know the capi property names.

I got that list from ` Object.keys(sqlite3.capi).map(k => `${k}: any;`).join('\n')` on runtime.

Translated with www.DeepL.com/Translator (free version)

**Comment by sgbeal** [comment]
> I got that list from  Object.keys(sqlite3.capi) on runtime.

Just FYI, there's a human-readable dump of that at: <https://sqlite.org/wasm/doc/trunk/module-symbols.html>

That one is generated from the version of the wasm/js running on that server, and that server is updated frequently (so is often more current than the latest release).

**Comment by jbaiter** [comment]
Here's another attempt at type hints based on @mizchi's work, but much expanded and with docstrings (based on the official documentation):
https://gist.github.com/jbaiter/d4a2a22c6c15571062f25d1dfea73218

The low-level APIs are as of yet untested and only based on the documentation, but I'll try to update them if I (or somebody else!) notice any mistakes.

**Comment by tomayac** [comment]
Do you want to massage this into the existing PR?

**Comment by jbaiter** [comment]
Sure! Should I create a separate branch based on yours?
The type hints are probably going to need a few iterations of "real world" testing, and some of the structs and functions are from the upcoming 3.43 release (FTS5 auxilliary APIs), though.

**Comment by sgbeal** [comment]
Note that the fts5 pieces are not part of 3.43. They are still far from complete, in a branch, and the hope is to have them done by 3.44.

**Comment by jbaiter** [comment]
Thank you for the clarification! I'll leave them out until 3.44 at least then :-)

**Comment by tomayac** [comment]
> Sure! Should I create a separate branch based on yours? The type hints are probably going to need a few iterations of "real world" testing, and some of the structs and functions are from the upcoming 3.43 release (FTS5 auxilliary APIs), though.

If you're confident about the changes, just merge it into the existing branch, please.

**Comment by jbaiter** [comment]
So after doing some testing I think it'll take a while before these are really ready 🙈 
The polymorphism on the `DB#exec` API is especially complicated, since there's such a large number of possible combinations between the different parameter types, many of which have effects on the possible values of other parameters.

**Comment by sgbeal** [comment]
> The polymorphism on the DB#exec API is especially complicated

Trivia: early in the design that was two separate functions: one for executing single statements (optionally fetching their results) and one for an arbitrary number of statements (e.g. a db dump). It turned out to be really clumsy to use that way so they were merged. The side effects that would have on type information like that provided by this project was not considered for even a moment (none of us work with node or typescript, so this was nowhere on our radar).

Note also that....

1. We added the "1" suffix to oo1 to indicate that it's "version 1." If experiences shows us that we need to, we'll create oo2 with whatever API changes experience has called for by that point. SQLite's strong backwards compatibility guarantees apply to the oo1 API, so it won't change in backwards-incompatible ways, but new API families may be added.
2. We don't expect oo1 to be "the" solution to the problem of providing a high-level wrapper: we'd very much like to see clients create their own which better suite their needs.

**Comment by tantaman** [comment]
> we'd very much like to see clients create their own which better suite their needs.

fwiw, here's some type-safe wrappers: https://vlcn.io/docs/js/wasm
They currently use `wa-sqlite` (for various stability, concurrency and perf reasons at the time) as the default build but in a few release we'll roll the official SQLite build back in (I removed it in the past as the sqlite team was very much still iterating).

Along with React hooks if that's your bag: https://vlcn.io/docs/js/react & https://www.youtube.com/watch?v=RtOroKmh1DE

And, if you really like your types, TypeScript types generated from SQL queries --
https://github.com/vlcn-io/typed-sql

https://github.com/vlcn-io/typed-sql/assets/1009003/4459edb2-4a52-4641-819d-5805c04d943a

**Comment by jbaiter** [comment]
Small update on the typing work: There's one aspect of the polymorphism of the `DB#exec` API that is to my current knowledge impossible to express in TypeScript:

- The combination of `rowMode="stmt"` and `returnValue="resultRows"` is impossible and will lead to a runtime error
- *but*: There's a polymorphic variant of `exec` that allows arbitrary `string` values for `rowMode` (for a column name reference), and this overload is chosen if you have the above combination of parameters. This is *not* a problem of the API, since the column name references have to have a certain format (so a `stmt` column would be `$stmt` and thus not be in conflict), but it's impossible to express within TypeScript's type system.

**Comment by jbaiter** [comment]
Apart from the above, I've now tested most of the `oo1` API and am pretty confident that the types are correct. Not thoroughly tested so far are the lower-level APIs (in the `wasm`, `vfs` and `vtable` namespaces).
The updated `add-types` branch lives here: https://github.com/tomayac/sqlite-wasm/compare/add-types...jbaiter:sqlite-wasm:add-types

**Comment by jbaiter** [comment]
I've now added docstrings to each and every `sqlite3.capi` function, including the original C function signature, as well as a link to the online documentation. The docstrings are based on those in `sqlite.h`, but much shorter, usually only the headline and the first paragraph, at most lightly edited.
