### ISSUE TITLE
Load error in Node.js

### ISSUE THREAD

**Issue by nwtgck** [sqlite/sqlite-wasm#38]
Hi,

Thank you so much for wonderful project!

My environement is
```bash
$ node -v
v18.18.0
$ npm -v
9.8.1
```

`@sqlite.org/sqlite-wasm` is `3.43.1-build1`.

I tried to use @sqlite.org/sqlite-wasm in Node.js:
```js
import sqlite3InitModule from '@sqlite.org/sqlite-wasm';

const log = (...args) => console.log(...args);
const error = (...args) => console.error(...args);

log('Loading and initializing SQLite3 module...');
const sqlite3 = await sqlite3InitModule({
  print: log,
  printErr: error,
});
```

But, the code causes an error:

```
Loading and initializing SQLite3 module...
Exception loading sqlite3 module: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11) {
  cause: Error: not implemented... yet...
      at makeNetworkError (node:internal/deps/undici/undici:6893:35)
      at schemeFetch (node:internal/deps/undici/undici:11029:18)
      at node:internal/deps/undici/undici:10909:26
      at mainFetch (node:internal/deps/undici/undici:10926:11)
      at fetching (node:internal/deps/undici/undici:10883:7)
      at fetch2 (node:internal/deps/undici/undici:10761:20)
      at Object.fetch (node:internal/deps/undici/undici:11574:18)
      at fetch (node:internal/process/pre_execution:242:25)
      at instantiateAsync (file:///Users/...)
      at createWasm (file:///Users/...)
}
...
```

I confirmed `wasmBinaryFile` in `instantiateAsync()` is `file:///Users/.../node_modules/@sqlite.org/sqlite-wasm/sqlite-wasm/jswasm/sqlite3.wasm`. So the `fetch()` try to GET `file:///...` and causes the error.

I found `file://` is not allowed in undici, which is `fetch()` internal implementation.
* https://github.com/nodejs/undici/issues/2144

**Comment by tomayac** [comment]
So far there's no support for Node.js, since the persistence layer depends on Web APIs like the [origin private file system](https://web.dev/opfs). There might be a way to work around this, and I welcome attempts at trying to achieve this. At the moment, though, Node.js support is out of scope for this library. I'm closing this issue, but please keep posting if you get it to work.

**Comment by nwtgck** [comment]
Thank you so much for details. That is unfortunate... I hope Node.js will have  web-like API. Until then, I try to use <https://github.com/sql-js/sql.js>.

(I thought Node.js is supported because https://github.com/sqlite/sqlite-wasm/blob/54dc60cedace8bb04d13fcf41865fb68461a0412/sqlite-wasm/jswasm/sqlite3-node.mjs exists.)

**Comment by sgbeal** [comment]
Just for the record: in the upstream project we are in no way averse to node support but we do not explicitly support it ourselves because nobody within the project uses node in any capacity. Any improvements to node support will have to come from folks who use node and can feed those improvements back to us. In any case, the exception message in this ticket is _not_ from the upstream library.

**Comment by sgbeal** [comment]
> (I thought Node.js is supported because https://github.com/sqlite/sqlite-wasm/blob/54dc60cedace8bb04d13fcf41865fb68461a0412/sqlite-wasm/jswasm/sqlite3-node.mjs exists.)

It exists because users have provided enough details for us to create a bundle which can be loaded in node. Node, however, lacks _all_ of the persistent-db options supported by the JS API, so node is limited to transient databases. The error message in your stack trace is not from the library, but from some node-level voodoo and, being fully ignorant of node, i'm unable to guess as to where the problem lies there.

**Comment by ilap** [comment]
> Thank you so much for details. That is unfortunate... I hope Node.js will have web-like API. Until then, I try to use https://github.com/sql-js/sql.js.
> 
> (I thought Node.js is supported because https://github.com/sqlite/sqlite-wasm/blob/54dc60cedace8bb04d13fcf41865fb68461a0412/sqlite-wasm/jswasm/sqlite3-node.mjs exists.)

Use:  "@sqlite.org/sqlite-wasm": "github:sqlite/sqlite-wasm#node",
