### ISSUE TITLE
Prepared statements with wrapped worker

### ISSUE THREAD

**Issue by marcus-pousette** [sqlite/sqlite-wasm#69]
Is it possible to prepare statement when using the API from the wrapped worker? It seems only possible now to perform raw statements. If not, would love to have this feature!

**Comment by sgbeal** [comment]
> Is it possible to prepare statement when using the API from the wrapped worker?

If you mean with the worker1 API then no, that's not possible, because the controlling thread has no direct access to the sqlite API, which is loaded and running in its own separate thread. The sqlite-related resources are tied specifically to the thread they are loaded in and cannot be shared by any two threads. Only data which can pass through `postMessage()` can be shared across threads.

**Comment by g-regor** [comment]
You don't need to pass the statement object through `postMessage()`. You can keep it in the worker thread and just pass a reference to the main thread. Then the main thread can make the calls to the worker thread with the reference.

Statements are already stored in `__stmtMap`. If you pass the pointer as a reference, you can later get the statement object from it.
