### ISSUE TITLE
OpfsSAHPoolDb what does unlinking do, and why do I have to do it to clear up pool?

### ISSUE THREAD

**Issue by marcus-pousette** [sqlite/sqlite-wasm#70]
Hey!

I am trying to understand how to correctly manage databases I create with OpfsSAHPoolDB

Here is some code I have

```ts

const poolUtil = await sqlite3.installOpfsSAHPoolVfs({
            directory: "somewhere"
        });
        
const dbFileName = uuid()
const db = sqliteDb = new poolUtil.OpfsSAHPoolDb(dbFileName);

console.log(poolUtil.getFileNames()) // ["some uuid" ]
db.close() 
console.log(poolUtil.getFileNames()) // ["some uuid" ]
poolUtil.unlink(dbFileName)
console.log(poolUtil.getFileNames()) // []

```

It seem like if I don't call 'unlink'  I get "SAH pool is full. Cannot create file" error when creating to many different databases, even if I have closed the previous ones. 

However, the problem when calling unlink on close is that it seems to delete the database contents. I have a test where I have a database which I put some data in and I restart it and check whether I can read the same data back, and I manage to make the test pass if I don't call unlink after database closing. 

What does `unlink` do? Is it something I should called on databases that I have closed, but I might reopen later?

What is the drawback adding huge amount of capacity like below? and why is the default capacity very low?

```ts
poolUtil.reserveMinimumCapacity(very large number)
```

**Comment by tomayac** [comment]
@sgbeal Are you in a position to answer this question?

**Comment by sgbeal** [comment]
> It seem like if I don't call 'unlink' I get "SAH pool is full. Cannot create file" error when creating to many different databases, even if I have closed the previous ones.

That's correct. Closing them retains the contents under the mapped name. That slot is not freed until/unless it is unlinked.

> However, the problem when calling unlink on close is that it seems to delete the database contents. 

Of course it does because...

> What does unlink do? Is it something I should called on databases that I have closed, but I might reopen later?

"unlink" is the historical Unix name for "delete file."

> What is the drawback adding huge amount of capacity like below?

This particular VFS, to work around async-vs-sync incompatibilities, has to pre-open all handles and keep them open. Providing a large value will have a high memory cost and potentially (depending on the browser version) have as-yet-unknown performance implications.

If you require some massive number of individual databases, use the other OPFS VFS instead of this one. Both are documented at: https://sqlite.org/wasm/doc/trunk/persistence.md

**Comment by marcus-pousette** [comment]
Thank you for the quick response. 

> This particular VFS, to work around async-vs-sync incompatibilities, has to pre-open all handles and keep them open. Providing a large value will have a high memory cost and potentially (depending on the browser version) have as-yet-unknown performance implications.

Make sense, though I need to dive into the source code to understand fully why this is the case. What I am thinking about, that feels intuitive, is an api where I can close a handle to a file without deleting the file (with unlink). Now I think I can get this behaviour by terminating the WebWorker (because if you do that, the db files will persist but all access handles should be closed)

**Comment by sgbeal** [comment]
> ... though I need to dive into the source code to understand fully why this is the case.

Or read the docs linked to in my last post ;).

> What I am thinking about, that feels intuitive, is an api where I can close a handle to a file without deleting the file (with unlink).

i think two concepts are being confounded here. There are two levels of file abstraction here and each behaves differently.

The VFS itself has to pre-open some fixed number of OPFS SyncAccessHandles because that is the only way to provide _synchronous_ open() behavior to the C side of the API (opening an OPFS file via its own native API is, highly unfortunately, async, which makes it fundamentally incompatible with the C API). Those handles are, however, an internal level of abstraction for use in _simulating_ a synchronous filesystem for the C API. When you open a database, the VFS checks...

1) Is there already a "container" file mapped to that db name? If so, give that pre-opened handle back to the user. If not...
2) Do we have an open slot for a new db file? If so, persistently map it to that name and give the pre-opened handle back to the user. If not...
3) The filesystem is "full" (no more slots available).

When you close() a database, it is retained in OPFS and can be re-opened in step (1) of that check, but the actual OPFS file handle behind it necessarily _remains open_. When you unlink one of the slots, you are freeing it up for re-use in step (2) of that check, but the OPFS file handle behind still remains open. The handles are not actually closed (at the OPFS level) until the VFS itself is shut down (typically when its owning worker dies, but there's also an API call to do it).

**Comment by marcus-pousette** [comment]
thank you so much for explaining. It all makes sense now!
