### ISSUE TITLE
Missing last_insert_rowid API

### ISSUE THREAD

**Issue by g-regor** [sqlite/sqlite-wasm#85]
There seems to be missing OO/Worker API for `sqlite3_last_insert_rowid()`.

Currently it's only possible by executing `SELECT LAST_INSERT_ROWID()`.

`exec` should probably return the last inserted id via an argument, like `countChanges` makes it return `changeCount`.

**Comment by sgbeal** [comment]
The worker API is very specifically for minimal/toy uses only. That way of remote-controlling the db is far too limited for any serious work, so addeevery potential feature to it would be (A) a waste of development effort and (B) would further promote its use (something i very much do not want).

**Comment by sgbeal** [comment]
``

**Comment by g-regor** [comment]
That doesn't explain the missing API for OO.

**Comment by sgbeal** [comment]
Its lack in the oo1 API is an oversight but you don't need it: passing an oo1 db object to sqlite3.capi.sqlite3_last_insert_rowid() will work.

(please pardon brevity - am struggling to work with github from a phone)

**Comment by g-regor** [comment]
>Adding every potential feature to it would be (A) a waste of development effort and (B) would further encourage its use (something i very much do not want).

But that is the preferred option for this project.

>There are three ways to use SQLite Wasm:
> * [in the main thread with a wrapped worker](https://github.com/sqlite/sqlite-wasm/blob/main/README.md#in-a-wrapped-worker-with-opfs-if-available) (🏆 preferred option)
> * ...

**Comment by sgbeal** [comment]
> [in the main thread with a wrapped worker](https://github.com/sqlite/sqlite-wasm/blob/main/README.md#in-a-wrapped-worker-with-opfs-if-available) (🏆 preferred option)

That may be, but it's not with the worker1 API. The ideal situation, for such uses, is that the application defines and implements concrete interfaces between their application and the worker. e.g. posting a "getUserInfo" message instead of posting a "SELECT ..." to the worker1 interface. Implement the app-defined API in your app-specific worker and load sqlite3.[m]js directly from that worker. Worker1 is an app-agnostic API with _severe_ limitations imposed by the postMessage() communication model, as documented in the top section of <https://sqlite.org/wasm/doc/trunk/api-worker1.md>. Wrapping such work behind application-defined interfaces, and implementing them in an app-specific Worker,  eliminates, or at least drastically softens, some of those limitations.
